name: build-mojang-leveldb

on: [push]

jobs:
  build-mojang-leveldb:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: build
        id: build
        shell: cmd
        run: call build.cmd

      - name: release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: mojang-leveldb
          release_name: mojang-leveldb

      - name: upload
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           upload_url: ${{ steps.release.outputs.upload_url }}
           asset_path: "mojang-leveldb.zip"
           asset_name: "mojang-leveldb.zip"
           asset_content_type: application/zip